maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend/Craftsy
    - mvn clean package -DskipTests   # skip tests for now
  artifacts:
    paths:
      - Backend/Craftsy/target/*.jar
  only:
    refs:
      - main
    changes:
      - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend/Craftsy
    - mvn test -DskipTests || echo "Skipping tests for now"
  only:
    refs:
      - main
    changes:
      - Backend/**/*
