package com.example.craftsy.SignUpDelete.Entity;

import com.example.craftsy.images.Image;
import com.example.craftsy.messages.conversations.DirectConversation;
import com.example.craftsy.messages.conversations.GroupConversation;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.util.List;

/**
 * Users entity represents a registered user in the system.
 */
@Entity
@Table(name = "users")
public class Users {

    @Id // Primary Key and auto-generated by database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Unique username for login
    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 30, message = "Username must be between 3–30 characters")
    @Column(nullable = false, unique = true)
    private String username;

    // Display name shown to other users
    @NotBlank(message = "Display name is required")
    @Size(max = 50, message = "Display name cannot exceed 50 characters")
    @Column(nullable = false, unique = true)
    private String displayName;

    // Short biography
    @Size(max = 1000, message = "Bio cannot exceed 1000 characters")
    @Column(length = 1000)
    private String bio;

    // URL or path to profile picture
    private String profilePic;

    // User's craft specialties
    @Size(max = 255, message = "Craft specialties cannot exceed 255 characters")
    @Column(name = "craftSpecialties")
    private String craftSpecialties;

    // Number of followers
    private Integer followers = 0;

    // Number of users this user is following
    private Integer following = 0;

    // Email address
    private String email;

    // Hashed password
    @NotBlank(message = "Password is required")
    @Column(nullable = false)
    private String password;

    @ManyToOne
    @JoinColumn(name = "image_id")
    private Image image;

    // Default constructor
    public Users() {}

    // Full constructor
    public Users(String username, String displayName, String bio, String profilePic, String craftSpecialties,
                 Integer followers, Integer following, String email, String password) {
        this.username = username;
        this.displayName = displayName;
        this.bio = bio;
        this.profilePic = profilePic;
        this.craftSpecialties = craftSpecialties;
        this.followers = followers;
        this.following = following;
        this.email = email;
        this.password = password;
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public String getProfilePic() {
        return profilePic;
    }

    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }

    public String getCraftSpecialties() {
        return craftSpecialties;
    }

    public void setCraftSpecialties(String craftSpecialities) {
        this.craftSpecialties = craftSpecialities;
    }

    public Integer getFollowers() {
        return followers;
    }

    public void setFollowers(Integer followers) {
        this.followers = followers;
    }

    public Integer getFollowing() {
        return following;
    }

    public void setFollowing(Integer following) {
        this.following = following;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Image getImage() {
        return image;
    }

    public void setImage(Image image) {
        this.image = image;
    }
}
