package com.example.craftsy.SignUpDelete.Entity;


// JPA -> Map Java classes to Database
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import jakarta.persistence.*;


import lombok.Getter;
import lombok.Setter;



/**
 *
 * @author Alister Gan
 *
 */


// Create a table in database
@Entity
@Getter
@Setter
@Table(name = "users")
public class Users {

    @Id // Primary Key and auto-generated by database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String username;

    @Column(nullable = false, unique = true)
    private String displayName;

    @Column(length = 1000)
    private String bio;

    private String profilePic;

    @Column(name = "craftSpecialties")
    private String craftSpecialties;

    private Integer followers = 0;

    private Integer following = 0;

    private String email;

    @Column(nullable = false)
    private String password;
}
