package com.example.craftsy.FollowingFollowers.Entity;


// JPA -> Map Java classes to Database
import com.example.craftsy.SignUpDelete.Entity.Users;
import jakarta.persistence.*;


import lombok.Getter;
import lombok.Setter;
import org.apache.catalina.User;


/**
 *
 * @author Alister Gan
 *
 */


// Create a table in database
@Entity
@Getter
@Setter                                     // Unique Constraints ensure follower_id and following_id cannot appear twice
@Table(name = "follow", uniqueConstraints = {@UniqueConstraint(columnNames = {"follower_id", "following_id"})})
public class Follow {

    @Id // Primary Key and auto-generated by database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // Store reference to the IDs in the Users Table (ID as foreign Key)
    // follower_id is the foreign key that references the user who is following
    @ManyToOne
    @JoinColumn(name = "follower_id", nullable = false)
    private Users follower;


    // following_id is the foreign key that references the user who is being followed
    @ManyToOne
    @JoinColumn(name = "following_id", nullable = false)
    private Users following;

    @Column(nullable = false)
    private String status = "PENDING"; // Values: "PENDING" or "ACCEPTED"

}
